import type { AppData, Filter, Order } from './types';
import { isReady } from './csv';
import { checkoutUrl } from './license';

export const escapeHtml = (value: unknown) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]!);
export const money = (amount: number, currency = 'USD') => new Intl.NumberFormat('en', { style: 'currency', currency }).format(amount);

export function header(active = ''): string {
  return `<a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header"><a class="wordmark" href="/" data-link aria-label="Paid Before Ship Gate home"><span class="gate-mark" aria-hidden="true">▰</span><span>Paid Before<br>Ship Gate</span></a>
  <nav aria-label="Main navigation"><a href="/?demo=1" data-link ${active === 'demo' ? 'aria-current="page"' : ''}>Demo</a><a href="/board" data-link ${active === 'board' ? 'aria-current="page"' : ''}>Order board</a><a href="/privacy" data-link ${active === 'privacy' ? 'aria-current="page"' : ''}>Privacy</a></nav></header>`;
}

export function footer(): string {
  return `<footer><p><strong>Paid Before Ship Gate</strong><br><span>Check payment before an order is packed.</span></p><p><a href="/privacy" data-link>Privacy</a> · <a href="/terms" data-link>Terms</a><br><a href="https://sociobot.in" rel="external">Built by Param Factory <span class="sr-only">(external)</span></a> · v1.0.2</p><p class="made-note">Hero art was generated for this product.</p></footer>`;
}

export function home(paidAccess = false): string {
  return `${header()}<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">A payment checkpoint for packing</p><h1 tabindex="-1">Stop unpaid orders before packing</h1><p class="lede">For small sellers who let customers pay later and need a clear check before packing.</p><div class="hero-action"><a class="button primary" href="/?demo=1" data-link>Try it with sample data</a><span>Open five sample orders: three ready and two on hold.</span></div><ul class="plain-facts"><li>Works offline after the first visit</li><li>Order data stays in this browser</li><li>$39 once for encryption and customer hold rules</li></ul></div><div class="hero-art"><picture><source type="image/avif" srcset="/assets/dispatch-gate-480.avif 480w, /assets/dispatch-gate.avif 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw"><source type="image/webp" srcset="/assets/dispatch-gate-480.webp 480w, /assets/dispatch-gate.webp 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw"><img src="/assets/dispatch-gate.jpg" srcset="/assets/dispatch-gate-480.jpg 480w, /assets/dispatch-gate.jpg 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw" width="768" height="512" alt="A printed collage of parcels waiting at a payment checkpoint." fetchpriority="high" decoding="async"></picture><span class="stamp stamp-hold">HOLD</span><span class="tape" aria-hidden="true"></span></div></section>
  <section class="live-preview" aria-labelledby="preview-title"><div class="section-intro"><p class="eyebrow">The order board</p><h2 id="preview-title">See which orders are ready to pack</h2><p>See each order’s total, payments, and hold status on one board.</p></div><div class="preview-sheet"><div class="preview-top"><strong>Current pack list</strong><span>2 ready · 2 held</span></div><div class="preview-row"><span><b>SO-1048</b> Moss & Thread</span><span class="status ready">Ready · paid</span></div><div class="preview-row"><span><b>SO-1049</b> Brighton Pantry</span><span class="status held">Hold · $94.50 due</span></div><div class="preview-row"><span><b>SO-1050</b> Ada Studio</span><span class="status ready">Ready · no hold</span></div><div class="preview-row"><span><b>SO-1051</b> Moss & Thread</span><span class="status held">Hold · $125.00 due</span></div></div></section>
  <section class="how" aria-labelledby="how-title"><div><p class="eyebrow">How it works</p><h2 id="how-title">Turn an order spreadsheet into a pack list</h2></div><ol><li><span>1</span><div><h3>Import order spreadsheets (CSV)</h3><p>Use an order number and total. Optional details are preserved when a returning order omits them.</p></div></li><li><span>2</span><div><h3>Match payments</h3><p>Successful or settled payments in the order currency make held orders ready.</p></div></li><li><span>3</span><div><h3>Export the pack list</h3><p>Only paid or manually approved orders are exported.</p></div></li></ol></section>
  <section class="boundaries" aria-labelledby="boundaries-title"><div><p class="eyebrow">Payment exceptions and limits</p><h2 id="boundaries-title">You approve every payment exception</h2></div><div><p>This tool does not score customers, collect debts, reserve stock, contact anyone, process payments, or print shipping labels.</p><p>New orders need only an order number and total. Material changes to returning orders require your review.</p></div></section>
  <section class="price" aria-labelledby="price-title"><div class="price-stamp"><span>$39</span><small>one time</small></div><div><p class="eyebrow">Paid features</p><h2 id="price-title">Encrypt records and save customer hold rules</h2><p>The free board includes imports, payment checks, approvals, backups, and pack lists. Pay once to add encrypted local storage and customer hold rules.</p><div class="button-row"><a class="button primary" href="${checkoutUrl}">Buy encryption and hold rules <span class="sr-only">(external checkout)</span></a><button class="button secondary" type="button" data-action="show-license">${paidAccess ? 'Manage paid access' : 'Restore paid access'}</button></div><p class="legal-note">Checkout opens a Dodo-hosted payment page. Returns follow the linked <a href="https://dodopayments.com/buyer-terms" rel="external">Dodo Buyer Terms <span class="sr-only">(external)</span></a>.</p></div></section></main>${footer()}`;
}

function orderRow(order: Order, demo: boolean, paidAccess: boolean): string {
  const ready = isReady(order);
  const due = Math.max(0, order.total - order.paid);
  const currency = order.currency || 'USD';
  if (order.packedAt) return `<article class="order-row is-packed" data-order-id="${escapeHtml(order.id)}"><div class="order-main"><div><span class="order-number">${escapeHtml(order.orderNumber)}</span><h3>${escapeHtml(order.customer)}</h3><span class="order-date">Packed ${escapeHtml(order.packedAt.slice(0, 10))}</span></div><div class="money"><strong>${money(order.total, currency)}</strong><span>${money(order.paid, currency)} paid</span></div></div><div class="order-gate"><span class="status packed">Packed</span><button class="text-button" data-action="restore-packed">Return to active board</button></div></article>`;
  return `<article class="order-row ${ready ? 'is-ready' : 'is-held'}" data-order-id="${escapeHtml(order.id)}"><div class="order-main"><div><span class="order-number">${escapeHtml(order.orderNumber)}</span><h3>${escapeHtml(order.customer)}</h3><span class="order-date">${escapeHtml(order.createdAt)}</span></div><div class="money"><strong>${money(order.total, currency)}</strong><span>${money(order.paid, currency)} paid</span></div></div><div class="order-gate"><span class="status ${ready ? 'ready' : 'held'}">${ready ? (order.override ? 'Ready · approval' : order.hold ? 'Ready · paid' : 'Ready · no payment hold') : `Hold · ${money(due, currency)} due`}</span><button class="text-button" data-action="toggle-hold" aria-pressed="${order.hold}">${order.hold ? 'Remove payment hold' : 'Require payment'}</button>${!ready ? `<button class="button small" data-action="approval">Record approval</button>` : ''}${order.override ? `<p class="override-note">Approval by ${escapeHtml(order.override.name)}: ${escapeHtml(order.override.reason)}</p>` : ''}${paidAccess || demo ? `<button class="text-button save-rule" data-action="save-rule">Save customer hold rule for ${escapeHtml(order.customer)}</button>` : ''}</div></article>`;
}

export function board(data: AppData, demo: boolean, filter: Filter, paidAccess: boolean): string {
  const filtered = data.orders.filter((order) => filter === 'all' || (filter === 'ready' ? isReady(order) : filter === 'hold' ? !order.packedAt && !isReady(order) : Boolean(order.packedAt)));
  const readyCount = data.orders.filter(isReady).length;
  const heldCount = data.orders.filter((order) => !order.packedAt && !isReady(order)).length;
  const packedCount = data.orders.filter((order) => order.packedAt).length;
  const content = data.orders.length === 0 ? `<div class="empty-state"><span class="empty-box" aria-hidden="true">□</span><h2>No orders are waiting</h2><p>Import an order spreadsheet (CSV) or add one order to start the board.</p><button class="button primary" data-action="import-orders">Import order spreadsheet (CSV)</button></div>` : `<h2 class="sr-only">Orders</h2><div class="filter-bar" role="group" aria-label="Filter orders"><button data-filter="all" aria-pressed="${filter === 'all'}">All <span>${data.orders.length}</span></button><button data-filter="ready" aria-pressed="${filter === 'ready'}">Ready <span>${readyCount}</span></button><button data-filter="hold" aria-pressed="${filter === 'hold'}">On hold <span>${heldCount}</span></button><button data-filter="packed" aria-pressed="${filter === 'packed'}">Packed <span>${packedCount}</span></button></div><div class="order-list">${filtered.length ? filtered.map((order) => orderRow(order, demo, paidAccess)).join('') : `<div class="no-match"><h3>No ${filter} orders</h3><p>Choose another filter to see the rest of the board.</p></div>`}</div>`;
  const firstReady = data.orders.find(isReady);
  const firstHeld = data.orders.find((order) => !order.packedAt && !isReady(order));
  const demoPreview = demo && firstReady && firstHeld ? `<section class="demo-first-look" aria-label="Sample orders"><p class="eyebrow">Sample orders</p><div><article><span><b>${escapeHtml(firstReady.orderNumber)}</b> · ${escapeHtml(firstReady.customer)}</span><strong>${money(firstReady.total, firstReady.currency)}</strong><span class="status ready">Ready · paid</span></article><article><span><b>${escapeHtml(firstHeld.orderNumber)}</b> · ${escapeHtml(firstHeld.customer)}</span><strong>${money(firstHeld.total, firstHeld.currency)}</strong><span class="status held">Hold · ${money(Math.max(0, firstHeld.total - firstHeld.paid), firstHeld.currency)} due</span></article></div></section>` : '';
  return `${header(demo ? 'demo' : 'board')}${demo ? `<aside class="demo-banner" aria-label="Demo mode"><span><strong>Demo</strong> — sample data, nothing is saved</span><span><button data-action="reset-demo">Reset demo</button><a href="/board" data-action="leave-demo">Start for real</a></span></aside>${demoPreview}` : ''}<main id="main" class="board-page"><div class="board-heading"><div><p class="eyebrow">Packing checkpoint</p><h1 tabindex="-1">Choose today’s pack list</h1><p>Only paid or manually approved orders reach the export.</p></div><div class="batch-count"><span>${readyCount}</span><small>ready now</small></div></div><section class="board-tools" aria-label="Order tools"><button class="button primary" data-action="import-orders">Import order spreadsheet (CSV)</button><button class="button secondary" data-action="import-payments">Import payment spreadsheet (CSV)</button><button class="button secondary" data-action="add-order">Add one order</button><button class="button ink" data-action="export-pack" ${readyCount ? '' : 'disabled'}>Export pack list</button><button class="button secondary" data-action="mark-packed" ${readyCount ? '' : 'disabled'}>Mark ready orders packed</button><input id="orders-file" type="file" accept=".csv,text/csv" hidden><input id="payments-file" type="file" accept=".csv,text/csv" hidden></section><div id="notice" class="notice" aria-live="polite"></div>${content}<section class="desk-settings" aria-labelledby="records-title"><div><p class="eyebrow">Records</p><h2 id="records-title">Export or restore a workspace backup</h2><p>Download a complete backup file (JSON) whenever you need one.</p></div><div class="settings-actions"><button class="button secondary" data-action="export-backup">Export backup</button><button class="button secondary" data-action="import-backup">Import backup</button><input id="backup-file" type="file" accept="application/json,.json" hidden>${!demo ? (paidAccess ? `<button class="button secondary" data-action="vault">${document.body.dataset.vaultOpen === 'true' ? 'Turn off encryption' : 'Encrypt this device'}</button><button class="button secondary" data-action="show-license">Manage paid access</button>` : `<a class="text-link" href="/#price-title" data-link>Get encryption and customer hold rules for $39</a><button class="button secondary" data-action="show-license">Restore paid access</button>`) : ''}</div></section></main>${footer()}`;
}

export function legalPage(kind: 'privacy' | 'terms'): string {
  const privacy = kind === 'privacy';
  return `${header(kind)}<main id="main" class="prose-page"><p class="eyebrow">${privacy ? 'Privacy' : 'Terms'}</p><h1 tabindex="-1">${privacy ? 'Your records stay under your control' : 'Terms for using the order board'}</h1>${privacy ? `<h2>Data on this device</h2><p>Order records, payment amounts, customer hold rules, and approvals are stored in this browser. Demo changes use a separate memory-only workspace.</p><h2>Network requests</h2><p>The app makes no analytics or advertising requests. It contacts Sociobot only to verify a saved, returned, or newly entered paid license.</p><h2>License storage</h2><p>A valid license token stays in this browser until you choose Remove saved license. Rejected tokens are not saved.</p><h2>Encryption</h2><p>Paid users can encrypt the local workspace with a passphrase. The passphrase is not stored, so you enter it again after reloading.</p><h2>Files you choose</h2><p>Spreadsheet and backup files are read on this device. The app does not upload their contents.</p>` : `<h2>Purpose</h2><p>This tool is an operational checklist. You choose which payment file to import and review its matches. You decide each payment hold and approval.</p><h2>Not financial advice</h2><p>The app does not assess creditworthiness, confirm bank settlement, or replace your accounting records.</p><h2>One-time purchase and returns</h2><p>Paid features cost $39 once for encrypted local storage and customer hold rules. Checkout opens a Dodo-hosted payment page.</p><p>Returns follow the linked <a href="https://dodopayments.com/buyer-terms" rel="external">Dodo Buyer Terms <span class="sr-only">(external)</span></a>. Inactive licenses lock paid features.</p><h2>Your responsibility</h2><p>Check imported amounts before dispatch. Keep a backup and keep your encryption passphrase available for reloads.</p>`}<p>Last updated: 29 August 2026.</p></main>${footer()}`;
}

export function notFound(): string { return `${header()}<main id="main" class="not-found"><div class="lost-parcel" aria-hidden="true">?</div><p class="eyebrow">404</p><h1 tabindex="-1">Page not found</h1><p>This page does not exist. Check the address or return home.</p><a class="button primary" href="/" data-link>Return home</a></main>${footer()}`; }

export function dialogShell(content: string): HTMLDialogElement {
  const dialog = document.createElement('dialog'); dialog.className = 'app-dialog'; dialog.innerHTML = content; document.body.append(dialog); dialog.querySelectorAll('[data-close]').forEach((control) => control.addEventListener('click', () => dialog.close())); dialog.showModal(); return dialog;
}
