import type { AppData, Filter, Order } from './types';
import { isReady } from './csv';
import { checkoutUrl } from './license';

export const escapeHtml = (value: unknown) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]!);
export const money = (amount: number, currency = 'USD') => new Intl.NumberFormat('en', { style: 'currency', currency }).format(amount);

export function header(active = ''): string {
  return `<a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header"><a class="wordmark" href="/" data-link aria-label="Paid Before Ship Gate home"><span class="gate-mark" aria-hidden="true">▰</span><span>Paid Before<br>Ship Gate</span></a>
  <nav aria-label="Main navigation"><a href="/demo" data-link ${active === 'demo' ? 'aria-current="page"' : ''}>Demo</a><a href="/board" data-link ${active === 'board' ? 'aria-current="page"' : ''}>Order board</a><a href="/privacy" data-link ${active === 'privacy' ? 'aria-current="page"' : ''}>Privacy</a></nav></header>`;
}

export function footer(): string {
  return `<footer><p><strong>Paid Before Ship Gate</strong><br><span>Check payment before an order reaches the packing bench.</span></p><p><a href="/privacy" data-link>Privacy</a> · <a href="/terms" data-link>Terms</a><br><a href="https://sociobot.in" rel="external">Built by Param Factory <span class="sr-only">(external)</span></a> · v1.0.0</p><p class="made-note">Hero art was generated for this product.</p></footer>`;
}

export function home(): string {
  return `${header()}<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">A checkpoint for the packing bench</p><h1 tabindex="-1">Stop unpaid orders before packing</h1><p class="lede">For small sellers who need a clear payment check before each packing batch.</p><div class="hero-action"><a class="button primary" href="/demo" data-link>Try it with sample data</a><span>See five orders sorted in one click.</span></div><ul class="plain-facts"><li>Works offline after the first visit</li><li>Order data stays in this browser</li><li>$39 once for encryption and saved rules</li></ul></div><div class="hero-art"><picture><source type="image/avif" srcset="/assets/dispatch-gate-480.avif 480w, /assets/dispatch-gate.avif 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw"><source type="image/webp" srcset="/assets/dispatch-gate-480.webp 480w, /assets/dispatch-gate.webp 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw"><img src="/assets/dispatch-gate.jpg" srcset="/assets/dispatch-gate-480.jpg 480w, /assets/dispatch-gate.jpg 768w" sizes="(max-width: 800px) calc(100vw - 40px), 52vw" width="768" height="512" alt="A printed collage of parcels waiting at a payment checkpoint." fetchpriority="high" decoding="async"></picture><span class="stamp stamp-hold">HOLD</span><span class="tape" aria-hidden="true"></span></div></section>
  <section class="live-preview" aria-labelledby="preview-title"><div class="section-intro"><p class="eyebrow">The checkpoint</p><h2 id="preview-title">Know what can reach the bench</h2><p>Payment evidence and hold rules meet in one compact order board.</p></div><div class="preview-sheet"><div class="preview-top"><strong>Today’s packing batch</strong><span>2 ready · 2 held</span></div><div class="preview-row"><span><b>SO-1048</b> Moss & Thread</span><span class="status ready">Ready · paid</span></div><div class="preview-row"><span><b>SO-1049</b> Brighton Pantry</span><span class="status held">Hold · $94.50 due</span></div><div class="preview-row"><span><b>SO-1050</b> Ada Studio</span><span class="status ready">Ready · no hold</span></div><div class="preview-row"><span><b>SO-1051</b> Moss & Thread</span><span class="status held">Hold · $125.00 due</span></div></div></section>
  <section class="how" aria-labelledby="how-title"><div><p class="eyebrow">Three passes</p><h2 id="how-title">Move from exports to a pack list</h2></div><ol><li><span>1</span><div><h3>Import orders</h3><p>Use order number, total, and optional customer or hold columns.</p></div></li><li><span>2</span><div><h3>Match payments</h3><p>Import payment amounts. The board clears fully paid orders.</p></div></li><li><span>3</span><div><h3>Export the pack list</h3><p>Held orders stay out unless a named person records a reason.</p></div></li></ol></section>
  <section class="boundaries" aria-labelledby="boundaries-title"><div><p class="eyebrow">A narrow guardrail</p><h2 id="boundaries-title">Your decision stays yours</h2></div><div><p>This tool does not score customers, collect debts, reserve stock, or contact anyone.</p><p>Imports may omit names, references, and dates. Only order numbers and amounts are required.</p></div></section>
  <section class="price" aria-labelledby="price-title"><div class="price-stamp"><span>$39</span><small>one time</small></div><div><p class="eyebrow">Paid desk kit</p><h2 id="price-title">Encrypt records and reuse hold rules</h2><p>The free board handles imports, payment checks, overrides, backups, and pack lists. Pay once to add an encrypted vault and saved customer rules.</p><div class="button-row"><a class="button primary" href="${checkoutUrl}">Buy the desk kit <span class="sr-only">(external checkout)</span></a><button class="button secondary" type="button" data-action="show-license">Paste a license</button></div><p class="legal-note">Sociobot is the merchant of record. See the <a href="/terms" data-link>terms</a> for refunds.</p></div></section></main>${footer()}`;
}

function orderRow(order: Order, demo: boolean, paidAccess: boolean): string {
  const ready = isReady(order);
  const due = Math.max(0, order.total - order.paid);
  const currency = order.currency || 'USD';
  return `<article class="order-row ${ready ? 'is-ready' : 'is-held'}" data-order-id="${escapeHtml(order.id)}"><div class="order-main"><div><span class="order-number">${escapeHtml(order.orderNumber)}</span><h3>${escapeHtml(order.customer)}</h3><span class="order-date">${escapeHtml(order.createdAt)}</span></div><div class="money"><strong>${money(order.total, currency)}</strong><span>${money(order.paid, currency)} paid</span></div></div><div class="order-gate"><span class="status ${ready ? 'ready' : 'held'}">${ready ? (order.override ? 'Ready · override' : order.hold ? 'Ready · paid' : 'Ready · no hold') : `Hold · ${money(due, currency)} due`}</span><button class="text-button" data-action="toggle-hold" aria-pressed="${order.hold}">${order.hold ? 'Remove payment hold' : 'Require payment'}</button>${!ready ? `<button class="button small" data-action="override">Record override</button>` : ''}${order.override ? `<p class="override-note">${escapeHtml(order.override.name)}: ${escapeHtml(order.override.reason)}</p>` : ''}${paidAccess || demo ? `<button class="text-button save-rule" data-action="save-rule">Apply this hold to ${escapeHtml(order.customer)}</button>` : ''}</div></article>`;
}

export function board(data: AppData, demo: boolean, filter: Filter, paidAccess: boolean): string {
  const filtered = data.orders.filter((order) => filter === 'all' || (filter === 'ready' ? isReady(order) : !isReady(order)));
  const readyCount = data.orders.filter(isReady).length;
  const heldCount = data.orders.length - readyCount;
  const content = data.orders.length === 0 ? `<div class="empty-state"><span class="empty-box" aria-hidden="true">□</span><h2>No orders are waiting</h2><p>Import an order CSV or add one order to start the board.</p><button class="button primary" data-action="import-orders">Import order CSV</button></div>` : `<h2 class="sr-only">Orders</h2><div class="filter-bar" role="group" aria-label="Filter orders"><button data-filter="all" aria-pressed="${filter === 'all'}">All <span>${data.orders.length}</span></button><button data-filter="ready" aria-pressed="${filter === 'ready'}">Ready <span>${readyCount}</span></button><button data-filter="hold" aria-pressed="${filter === 'hold'}">On hold <span>${heldCount}</span></button></div><div class="order-list">${filtered.length ? filtered.map((order) => orderRow(order, demo, paidAccess)).join('') : `<div class="no-match"><h3>No ${filter} orders</h3><p>Choose another filter to see the rest of the board.</p></div>`}</div>`;
  return `${header(demo ? 'demo' : 'board')}${demo ? `<aside class="demo-banner" aria-label="Demo mode"><span><strong>Demo</strong> — sample data, nothing is saved</span><span><button data-action="reset-demo">Reset demo</button><a href="/board" data-action="leave-demo">Start for real</a></span></aside>` : ''}<main id="main" class="board-page"><div class="board-heading"><div><p class="eyebrow">Packing checkpoint</p><h1 tabindex="-1">Choose today’s pack list</h1><p>Only paid or approved orders reach the export.</p></div><div class="batch-count"><span>${readyCount}</span><small>ready now</small></div></div><section class="board-tools" aria-label="Order tools"><button class="button primary" data-action="import-orders">Import order CSV</button><button class="button secondary" data-action="import-payments">Import payments</button><button class="button secondary" data-action="add-order">Add one order</button><button class="button ink" data-action="export-pack" ${readyCount ? '' : 'disabled'}>Export pack list</button><input id="orders-file" type="file" accept=".csv,text/csv" hidden><input id="payments-file" type="file" accept=".csv,text/csv" hidden></section><div id="notice" class="notice" aria-live="polite"></div>${content}<section class="desk-settings" aria-labelledby="records-title"><div><p class="eyebrow">Records</p><h2 id="records-title">Keep control of the file</h2><p>Download a full JSON backup whenever you need one.</p></div><div class="settings-actions"><button class="button secondary" data-action="export-backup">Export backup</button><button class="button secondary" data-action="import-backup">Import backup</button><input id="backup-file" type="file" accept="application/json,.json" hidden>${!demo ? (paidAccess ? `<button class="button secondary" data-action="vault">${document.body.dataset.vaultOpen === 'true' ? 'Turn off encryption' : 'Encrypt this device'}</button>` : `<a class="text-link" href="/#price-title" data-link>Get encryption and saved rules for $39</a>`) : ''}</div></section></main>${footer()}`;
}

export function legalPage(kind: 'privacy' | 'terms'): string {
  const privacy = kind === 'privacy';
  return `${header(kind)}<main id="main" class="prose-page"><p class="eyebrow">${privacy ? 'Privacy' : 'Terms'}</p><h1 tabindex="-1">${privacy ? 'Your records stay under your control' : 'Use the gate as a checklist'}</h1>${privacy ? `<h2>Data on this device</h2><p>Order records, payment amounts, rules, and overrides are stored in this browser. Demo changes use a separate memory-only workspace.</p><h2>Network requests</h2><p>The app makes no analytics or advertising requests. It contacts Sociobot only when you verify a paid license.</p><h2>Encryption</h2><p>Paid users can encrypt the local workspace with AES-GCM. The passphrase is not stored or recoverable.</p><h2>Files you choose</h2><p>CSV and backup files are read on this device. The app does not upload their contents.</p>` : `<h2>Purpose</h2><p>This tool is an operational checklist. You decide each hold, payment match, and override.</p><h2>Not financial advice</h2><p>The app does not assess creditworthiness, confirm bank settlement, or replace your accounting records.</p><h2>One-time purchase</h2><p>The $39 desk kit unlocks device encryption and saved customer rules. Sociobot and Dodo are the merchant of record. Refunds follow the checkout terms. Inactive licenses lock paid features.</p><h2>Your responsibility</h2><p>Check imported amounts before dispatch. Keep a backup and do not lose an encryption passphrase.</p>`}<p>Last updated: 28 August 2026.</p></main>${footer()}`;
}

export function notFound(): string { return `${header()}<main id="main" class="not-found"><div class="lost-parcel" aria-hidden="true">?</div><p class="eyebrow">404 · wrong dispatch lane</p><h1 tabindex="-1">This page missed the pack list</h1><p>The address may be old or mistyped.</p><a class="button primary" href="/" data-link>Return to the checkpoint</a></main>${footer()}`; }

export function dialogShell(content: string): HTMLDialogElement {
  const dialog = document.createElement('dialog'); dialog.className = 'app-dialog'; dialog.innerHTML = content; document.body.append(dialog); dialog.querySelector('[data-close]')?.addEventListener('click', () => dialog.close()); dialog.showModal(); return dialog;
}
